config/routes.rb
Rails.application.routes.draw do
  root 'static_page#home'
  resources :activities, only: %i[index show]
  resources :cities, only: :index

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
  has_many :tags_activities, dependent: :destroy
  has_many :tags, through: :tags_activities
  belongs_to :city
  validates :city_id, :title, :price, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  has_many :activities, dependent: :destroy
  validates :name, :weight, presence: true
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :tags_activities, dependent: :destroy
  has_many :activities, through: :tags_activities
  validates :name, :weight, presence: true
end

app/models/tags_activity.rb
# frozen_string_literal: true

class TagsActivity < ApplicationRecord
  belongs_to :tag
  belongs_to :activity
  validates :tag_id, :activity_id, presence: true
end

app/controllers/activities_controller.rb
# frozen_string_literal: true

class ActivitiesController < ApplicationController
  def index
    @presenter = ActivitiesPresenter.new(permitted_params_index)
  end

  def show
    @presenter = ActivityPresenter.new(permitted_params_show)
  end

  def permitted_params_index
    params.permit(:city_id, :order)
  end

  def permitted_params_show
    params.permit(:id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
# frozen_string_literal: true

class CitiesController < ApplicationController
  def index
    @presenter = CityPresenter.new(permitted_params)
  end

  def permitted_params
    params.permit(:city_id)
  end
end

app/controllers/static_page_controller.rb
# frozen_string_literal: true

class StaticPageController < ApplicationController
  def home; end
end

app/helpers/activities_helper.rb
# frozen_string_literal: true

module ActivitiesHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cities_helper.rb
# frozen_string_literal: true

module CitiesHelper
end

app/helpers/static_page_helper.rb
# frozen_string_literal: true

module StaticPageHelper
end

app/views/activities/index.html.erb
<div class="container">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= form_tag({}, {:method => :get}) do %>
        <%= select_tag :city_id, options_from_collection_for_select(@presenter.cities_list, 'id', 'name', :selected => params[:city_id]), prompt: "Город", class: "form-control" %>
        <%= select_tag :order, options_for_select({ "#{ I18n.t 'price_desc' }": "price_desc", "#{ I18n.t 'price_asc' }": "price_asc", "#{ I18n.t 'weight' }": "weight" }, :selected => params[:order]), prompt: "Сортировать по: ", class: "form-control" %>
        <%= submit_tag "Submit", class: "form-control" %>
      <% end %>
    </li>
  </ul>
</div>
<div class="row">
  <%= will_paginate @presenter.activities, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <% @presenter.activities.each do |activity| %>
    <% cache(activity) do %>
      <div class="col">
        <div class="card activity-card">
          <div class="container-md"> <img src=<%= activity.photo %> class="card-img-top card-img-top-activity" alt="..."> </div>
          <div class="card-body">
          <h5 class="card-title"><%=link_to  activity.title, activity_path(id: activity.id) %>
          <p class="card-text"><%= activity.price %> <%= activity.currency %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/activities/show.html.erb
<div class="row">
  <div class="containter-fluid">
    <div class="col">
      <div class="card">
        <img src=<%= @presenter.activity.photo %> class="card-img-top activity-image" alt="...">
        <h5 class="card-title"><%= @presenter.activity.title %>
        <div class="card-body">
        <p class="card-text"><%= @presenter.activity.price %> <%= @presenter.activity.currency %></p>
        <p class="card-text"><%= @presenter.activity.description %> </p>
      </div>
    </div>
  </div>
</div>

app/views/cities/index.html.erb
<div class="row">
  <%= will_paginate @presenter.activities_in_city, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <% @presenter.activities_in_city.each do |activity| %>
    <% cache(activity) do %>
      <div class="col">
        <div class="cities-card">
          <img src=<%= activity.photo %> class="card-img-top" alt="...">
          <div class="card-body">
          <h5 class="card-title"><%= activity.title %>
          <p class="card-text"><%= activity.price %> <%= activity.currency %></p>
           </div>
         </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kirillsavenkov97</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header class="d-flex justify-content-center py-3">
        <a href="/activities"> <img src="https://dcf0cc24-b4f8-4213-8ee9-46f32e416483.selcdn.net/assets/affiliate/600x90-23aaf7186c3cf24aae43d1152c086cd1401150bbf0e1fb44987df1bd8d3b4c7f.jpg"> </a>
      </header>
    </div>
    <%= yield %>
  </body>
</html>

app/views/static_page/home.html.erb
<title> Привет мир! </title>